### ISSUE TITLE
Odoo 12 Manifest - Error

### ISSUE THREAD

**Issue by conroyke56** [OCA/delivery-carrier#234]
Im getting the below error when i try to view a manifest for any carrier in odoo 12.

Any ideas why or how to fix?

THANKS

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-275>", line 2, in get_manifest_file
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/addons/base_delivery_carrier_label/wizard/manifest_wizard.py", line 33, in get_manifest_file
    self.carrier_id.delivery_type)
NotImplementedError: Manifest not implemented for 'fixed' carrier.

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard OCA code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to OCA, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Comment by conroyke56** [comment]
Sorry, was this not for the carrier delivery label default?
This is when the issue has started.

**Comment by pedrobaeza** [comment]
But you are developing an extra module, so the problem should be in that module you are developing.

**Comment by conroyke56** [comment]
No. Not at all. I just installed your modules onto Standard community version of Odoo 12. And this error comes up. There’s also another issue raised to do with manifest_wizard. I’m guessing maybe this is related. Even on clean install of odoo 12, same error.

**Comment by conroyke56** [comment]
Will you re-open?

**Comment by pedrobaeza** [comment]
You are still not putting detailed steps to reproduce the problem, not even which modules are involved. Any way, you have to reproduce it on OCA runbot for qualifying for an issue.

**Comment by conroyke56** [comment]
Damn. Absolutely no idea how to do that.
Any way Incan get help?

**Comment by pedrobaeza** [comment]
You have the button "Try me on runbot" on the README for trying that things, but how do you expect to get help with so little information?

**Comment by conroyke56** [comment]
I assume the error details Odoo provided may have the information Within it. But I guess not. 

All I have done is create a multi company database.
Inventory app.
One parent company. Two child.

Added the default label module. 

Created a delivery order from the child company.

Set the carrier
Marked the transfer as to do
 
Went to operations 

Manifest

Set the carrier and date. 

Continue. 

And the above error occurs.




Will try the runbot now.

**Comment by conroyke56** [comment]
Same error occurs on the runbot.

![F576475F-124C-46E9-8335-4D3CD586CB01](https://user-images.githubusercontent.com/33205454/69140268-48fdcc80-0b16-11ea-9e2e-03266b0c4979.png)
![Uploading 7B3500E9-F2D7-4BE6-8A17-4C68D963FB0B.png…]()

**Comment by pedrobaeza** [comment]
Ok, now you have detailed enough the steps to reproduce the problem, so I reopen the issue.

**Comment by conroyke56** [comment]
Thanks. Hopefully someone can reproduce and find a solution. 

Cheers.
