### ISSUE TITLE
Transfer validation error with TNT module 14.0

### ISSUE THREAD

**Issue by esafocus** [OCA/delivery-carrier#605]
## Module
delivery_tnt_oca

## Describe the bug
When I validate the shipment I get this error described below

## To Reproduce
1) Create a shipment with TNT courier;
2) Validate the transfer document

**Expected behavior**
It should validate the shipment, communicate the data to TNT, and generate the shipping document

**Additional context**
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/stock/models/stock_picking.py", line 973, in button_validate
    pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
  File "/opt/odoo/odoo/addons/sale_stock/models/stock.py", line 91, in _action_done
    res = super()._action_done()
  File "/opt/odoo/odoo/addons/stock/models/stock_picking.py", line 800, in _action_done
    self._send_confirmation_email()
  File "/opt/odoo/odoo/addons/delivery/models/stock_picking.py", line 179, in _send_confirmation_email
    pick.sudo().send_to_shipper()
  File "/opt/odoo/odoo/addons/delivery/models/stock_picking.py", line 221, in send_to_shipper
    res = self.carrier_id.send_shipping(self)[0]
  File "/opt/odoo/odoo-custom-addons/oca/delivery-carrier/delivery_state/models/delivery_carrier.py", line 11, in send_shipping
    res = super().send_shipping(pickings)
  File "/opt/odoo/odoo/addons/delivery/models/delivery_carrier.py", line 194, in send_shipping
    return getattr(self, '%s_send_shipping' % self.delivery_type)(pickings)
  File "/opt/odoo/odoo-custom-addons/oca/delivery-carrier/delivery_tnt_oca/models/delivery_carrier.py", line 166, in tnt_oca_send_shipping
    return [self.tnt_oca_create_shipping(p) for p in pickings]
  File "/opt/odoo/odoo-custom-addons/oca/delivery-carrier/delivery_tnt_oca/models/delivery_carrier.py", line 166, in <listcomp>
    return [self.tnt_oca_create_shipping(p) for p in pickings]
  File "/opt/odoo/odoo-custom-addons/oca/delivery-carrier/delivery_tnt_oca/models/delivery_carrier.py", line 173, in tnt_oca_create_shipping
    self._tnt_oca_action_label(picking)
  File "/opt/odoo/odoo-custom-addons/oca/delivery-carrier/delivery_tnt_oca/models/delivery_carrier.py", line 154, in _tnt_oca_action_label
    res = iar._get_report_from_name(report_name).render_qweb_text(picking.ids)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'ir.actions.report' object has no attribute 'render_qweb_text'

**Comment by esafocus** [comment]
The above problem has been fixed.
Unfortunately it doesn't work with TNT Italia, do you know if it's my problem or is the module not supported by TNT Italia?
